apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.database.name_volume }}
spec:
  accessModes:
    - {{ .Values.database.accessModes }}
  resources:
    requests:
      storage: {{ .Values.database.storage }}