apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-database
spec:
  replicas: {{ .Values.database.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
      - name: {{ .Values.database.name }}
        image: {{ .Values.database.image }}
        volumeMounts:
        - name: {{ .Release.Name }}-{{ .Values.database.name_volume }}
          mountPath: {{ .Values.database.mountPath }}
      volumes:
      - name: {{ .Release.Name }}-{{ .Values.database.name_volume }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.database.name_volume }}
