apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-database
spec:
  type: {{ .Values.database.type }}
  selector:
    app: {{ .Values.database.name }}
  ports:
  - protocol: {{ .Values.database.protocol }}
    port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.targetport }}
