apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-database
  template:
    metadata:
      labels:
        app: mongodb-database
    spec:
      containers:
      - name: mongodb-database
        image: mongo:8.0.3

