---
- name: Actualizar el servidor
  dnf:
    update_cache: yes
    upgrade: dist

- name: Instalar Apache y habilitar servicio
  dnf:
    name: httpd
    state: present
  notify:
    - Iniciar Apache

- name: Instalar PHP y extensiones
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-common
    - php-mysql
    - php-xml
    - php-xmlrpc
    - php-curl
    - php-gd
    - php-cli
    - php-imap
    - php-mbstring
    - php-opcache
    - php-soap
    - php-zip
    - php-intl

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes

- name: Configurar permisos para WordPress
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes

- name: Configurar archivo wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Configurar Apache para WordPress
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Activar configuración de WordPress en Apache
  command: a2ensite wordpress.conf

- name: Desactivar sitio predeterminado de Apache
  command: a2dissite 000-default.conf

- name: Recargar Apache
  service:
    name: httpd
    state: reloaded
