---
- name: Actualizar el servidor
  dnf:
    name: "*"
    update_cache: yes
    state: latest

- name: Instalar Apache y habilitar servicio
  dnf:
    name: httpd
    state: present

- name: Instalar PHP y extensiones
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-common
    - php-mysqlnd
    - php-xml
    - php-curl
    - php-gd
    - php-cli
    - php-mbstring
    - php-opcache
    - php-soap
    - php-zip
    - php-intl

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes

- name: Configurar permisos para WordPress
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: apache
    group: apache
    mode: '0755'
    recurse: yes

- name: Configurar archivo wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: apache
    group: apache
    mode: '0644'

- name: Configurar Apache para WordPress
  template:
    src: wordpress.conf.j2
    dest: /etc/httpd/conf.d/wordpress.conf

- name: Recargar Apache
  service:
    name: httpd
    state: reloaded
