---
- name: Actualizar el servidor
  apt:
    update_cache: yes
    upgrade: dist

- name: Instalar Apache y habilitar el servicio
  apt:
    name: apache2
    state: present

- name: Asegurar que Apache está habilitado y corriendo
  service:
    name: apache2
    state: started
    enabled: yes

- name: Instalar PHP y extensiones
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-common
    - php-mysql
    - php-xml
    - php-curl
    - php-gd
    - php-cli
    - php-mbstring
    - php-opcache
    - php-soap
    - php-zip
    - php-intl

- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes

- name: Configurar permisos para WordPress
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes

- name: Configurar archivo wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Configurar Apache para WordPress
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Habilitar sitio de WordPress en Apache
  command: a2ensite wordpress.conf

- name: Deshabilitar el sitio predeterminado de Apache
  command: a2dissite 000-default.conf

- name: Habilitar módulo de reescritura de Apache
  command: a2enmod rewrite

- name: Recargar Apache
  service:
    name: apache2
    state: reloaded
