apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nestjs-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: nestjs
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: MONGODB_URI
          value: mongodb://{{ .Release.Name }}-mongodb-database:27017/nestjs
