apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nestjs-backend
spec:
  type: {{ .Values.backend.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
  - protocol: {{ .Values.backend.protocol }}
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.targetport }}
