---
- name: Instalar MariaDB y dependencias
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present
    update_cache: yes

- name: Iniciar y habilitar MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Asegurar instalación de MariaDB
  block:
    - name: Instalar expect para manejar respuestas automáticas
      apt:
        name: expect
        state: present

    - name: Asegurar MariaDB con mysql_secure_installation
      expect:
        command: mysql_secure_installation
        responses:
          "Enter current password for root (enter for none):": ""
          "Set root password? [Y/n]": "Y"
          "New password:": "USER@@123"
          "Re-enter new password:": "USER@@123"
          "Remove anonymous users? [Y/n]": "Y"
          "Disallow root login remotely? [Y/n]": "Y"
          "Remove test database and access to it? [Y/n]": "Y"
          "Reload privilege tables now? [Y/n]": "Y"

- name: Instalar dependencias de Ansible para manejar MySQL
  apt:
    name: python3-pymysql
    state: present

- name: Crear base de datos para WordPress
  mysql_db:
    name: wordpress_db
    state: present

- name: Crear usuario para WordPress
  mysql_user:
    name: wordpress_user
    password: USER@@123
    priv: "wordpress_db.*:ALL"
    host: localhost
    state: present
